SET IDENTITY_INSERT [dbo].[Buildings] ON
INSERT [dbo].[Buildings] ([Id], [Name], [Address], [ShortName], [Info]) VALUES (1, N'Главный корпус', N'пр. Ленина 33', N'ГК', NULL)
INSERT [dbo].[Buildings] ([Id], [Name], [Address], [ShortName], [Info]) VALUES (2, N'Учебный корпус №1', N'ул. Анохина 20', NULL, NULL)
INSERT [dbo].[Buildings] ([Id], [Name], [Address], [ShortName], [Info]) VALUES (3, N'Учебный корпус №2', N'наб. Гюллинга 17', NULL, NULL)
INSERT [dbo].[Buildings] ([Id], [Name], [Address], [ShortName], [Info]) VALUES (4, N'Учебный корпус №3', N'пр. Александра Невского 8', NULL, NULL)
INSERT [dbo].[Buildings] ([Id], [Name], [Address], [ShortName], [Info]) VALUES (5, N'Учебный корпус №4', N'пр. Александра Невского 48', NULL, NULL)
INSERT [dbo].[Buildings] ([Id], [Name], [Address], [ShortName], [Info]) VALUES (6, N'Учебно-лабораторный корпус №5', N'ул. Университетская 10', NULL, NULL)
INSERT [dbo].[Buildings] ([Id], [Name], [Address], [ShortName], [Info]) VALUES (7, N'Учебно-лабораторный корпус №6', N'ул. Университетская 10а', NULL, NULL)
INSERT [dbo].[Buildings] ([Id], [Name], [Address], [ShortName], [Info]) VALUES (8, N'Учебный корпус №7', N'наб. Варкауса 3', NULL, NULL)
INSERT [dbo].[Buildings] ([Id], [Name], [Address], [ShortName], [Info]) VALUES (9, N'Учебный корпус №8', N'ул. Ломоносова 65', NULL, NULL)
INSERT [dbo].[Buildings] ([Id], [Name], [Address], [ShortName], [Info]) VALUES (10, N'Учебный корпус №9', N'пр. Ленина 31', NULL, NULL)
INSERT [dbo].[Buildings] ([Id], [Name], [Address], [ShortName], [Info]) VALUES (11, N'Теоретический корпус', N'ул. Красноармейская 31', N'ТК', NULL)
INSERT [dbo].[Buildings] ([Id], [Name], [Address], [ShortName], [Info]) VALUES (12, N'Морфологический корпус', N'ул. Фрунзе 31', NULL, NULL)
INSERT [dbo].[Buildings] ([Id], [Name], [Address], [ShortName], [Info]) VALUES (13, N'Виварий', N'ул. Красноармейская 31Б', NULL, NULL)
INSERT [dbo].[Buildings] ([Id], [Name], [Address], [ShortName], [Info]) VALUES (14, N'Общежитие №1', N'ул. Ломоносова 63', NULL, NULL)
INSERT [dbo].[Buildings] ([Id], [Name], [Address], [ShortName], [Info]) VALUES (15, N'Общежитие №3', N'ул. Красноармейская 31А', NULL, NULL)
INSERT [dbo].[Buildings] ([Id], [Name], [Address], [ShortName], [Info]) VALUES (16, N'Общежитие №4', N'ул. Белорусская 15', NULL, NULL)
INSERT [dbo].[Buildings] ([Id], [Name], [Address], [ShortName], [Info]) VALUES (17, N'Общежитие №5', N'пр. Ленина 11Б', NULL, NULL)
INSERT [dbo].[Buildings] ([Id], [Name], [Address], [ShortName], [Info]) VALUES (18, N'Общежитие №6', N'ул. Белорусская 17', NULL, NULL)
INSERT [dbo].[Buildings] ([Id], [Name], [Address], [ShortName], [Info]) VALUES (19, N'Общежитие №7', N'ул. Фрунзе 7А', NULL, NULL)
INSERT [dbo].[Buildings] ([Id], [Name], [Address], [ShortName], [Info]) VALUES (20, N'Общежитие №8', N'ул. Суорявская 5', NULL, NULL)
INSERT [dbo].[Buildings] ([Id], [Name], [Address], [ShortName], [Info]) VALUES (21, N'Гараж и лабораторный ангар ФТФ', N'ул. Калевалы 15А', NULL, NULL)
SET IDENTITY_INSERT [dbo].[Buildings] OFF