SET IDENTITY_INSERT [dbo].[Departments] ON
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (1, N'Кафедра нормальной анатомии и гистологии', NULL, 1)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (2, N'Кафедра топографической и патологической анатомии', NULL, 1)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (3, N'Кафедра физиологии человека и животных', NULL, 1)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (4, N'Кафедра иностранных языков медико-биологических специальностей', NULL, 1)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (5, N'Кафедра пропедевтики внутренних болезней', NULL, 1)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (6, N'Кафедра фармакологии и ОЭФ', NULL, 1)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (7, N'Кафедра факультетской терапии', NULL, 1)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (8, N'Кафедра госпитальной хирургии', NULL, 1)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (9, N'Кафедра психиатрии', NULL, 1)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (10, N'Кафедра неврологии', NULL, 1)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (11, N'Кафедра акушерства и гинекологии', NULL, 1)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (12, N'Кафедра общей и факультетской хирургии', NULL, 1)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (13, N'Кафедра госпитальной терапии', NULL, 1)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (14, N'Кафедра педиатрии', NULL, 1)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (15, N'Кафедра критической и респираторной медицины', NULL, 1)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (16, N'Кафедра детской хирургии', NULL, 1)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (17, N'Кафедра лучевой диагностики и лучевой терапии', NULL, 1)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (18, N'Кафедра семейной медицины (общей врачебной практики)', NULL, 1)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (19, N'Кафедра инфекционных болезней с курсом эпидемиологии', NULL, 1)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (20, N'Кафедра бухгалтерского учета, анализа хозяйственной деятельности и аудита', NULL, 2)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (21, N'Кафедра теоретической экономики и государственного и муниципального управления', NULL, 2)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (22, N'Кафедра экономической теории и финансов', NULL, 2)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (23, N'Кафедра менеджмента', NULL, 2)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (24, N'Кафедра экономики и управления производством', NULL, 2)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (25, N'Кафедра архитектуры, строительных конструкций и геотехники', NULL, 3)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (26, N'Кафедра организации строительного производства', NULL, 3)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (27, N'Кафедра начертательной геометрии и инженерной графики', NULL, 3)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (28, N'Кафедра механики', NULL, 3)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (29, N'Кафедра водоснабжения, гидравлики и водоотведения', NULL, 3)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (30, N'Кафедра систем автоматизированного проектирования', NULL, 3)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (31, N'Кафедра политологии', NULL, 4)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (32, N'Кафедра социологии', NULL, 4)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (33, N'Кафедра социальной работы', NULL, 4)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (34, N'Кафедра международных отношений', NULL, 4)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (35, N'Кафедра иностранных языков факультета политических и социальных наук', NULL, 4)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (36, N'Кафедра финского языка и литературы', NULL, 5)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (37, N'Кафедра карельского и вепсского языков', NULL, 5)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (38, N'Кафедра агрономии, землеустройства и кадастров', NULL, 6)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (39, N'Кафедра зоотехнии, товароведения и экспертизы продовольственных товаров', NULL, 6)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (40, N'Кафедра механизации сельскохозяйственного производства', NULL, 6)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (41, N'Кафедра общей физики', NULL, 7)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (42, N'Кафедра физики твердого тела', NULL, 7)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (43, N'Кафедра информационно-измерительных систем и физической электроники', NULL, 7)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (44, N'Кафедра электроники и электроэнергетики', NULL, 7)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (45, N'Кафедра энергообеспечения предприятий и энергосбережения', NULL, 7)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (46, N'Кафедра русского языка', NULL, 15)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (47, N'Кафедра русской литературы и журналистики', NULL, 15)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (48, N'Кафедра германской филологии', NULL, 15)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (49, N'Кафедра классической филологии', NULL, 15)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (50, N'Кафедра кафедра скандинавских языков', NULL, 15)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (51, N'Кафедра общей химии', NULL, 8)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (52, N'Кафедра ботаники и физиологии растений', NULL, 8)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (53, N'Кафедра зоологии и экологии', NULL, 8)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (54, N'Кафедра молекулярной биологии, биологической и органической химии', NULL, 8)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (55, N'Кафедра геологии и геофизики', NULL, 14)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (56, N'Кафедра горного дела', NULL, 14)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (57, N'Кафедра всеобщей истории', NULL, 9)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (58, N'Кафедра истории дореволюционной России', NULL, 9)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (59, N'Кафедра отечественной истории (послереволюционный период)', NULL, 9)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (60, N'Кафедра истории стран Северной Европы', NULL, 9)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (61, N'Кафедра архивоведения и специальных исторических дисциплин', NULL, 9)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (62, N'Кафедра тяговых машин', NULL, 10)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (63, N'Кафедра технологии и оборудования лесного комплекса', NULL, 10)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (64, N'Кафедра промышленного транспорта и геодезии', NULL, 10)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (65, N'Кафедра лесного хозяйства', NULL, 10)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (66, N'Кафедра технологии металлов и ремонта', NULL, 10)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (67, N'Кафедра целлюлозно-бумажных и деревообрабатывающих производств', NULL, 10)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (68, N'Кафедра теории вероятностей и анализа данных', NULL, 11)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (69, N'Кафедра информатики и математического обеспечения', N'ИМО', 11)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (70, N'Кафедра математического анализа', NULL, 11)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (71, N'Кафедра прикладной математики и кибернетики', N'ПМиК', 11)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (72, N'Кафедра математического моделирования систем управления', NULL, 11)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (73, N'Кафедра геометрии и топологии', NULL, 11)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (74, N'Кафедра теории, истории государства и права', NULL, 13)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (75, N'Кафедра международного и конституционного права', NULL, 13)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (76, N'Кафедра гражданско-правовых дисциплин', NULL, 13)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (77, N'Кафедра уголовно-правовых дисциплин', NULL, 13)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (78, N'Кафедра иностранных языков гуманитарных факультетов', NULL, NULL)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (79, N'Кафедра иностранных языков технических факультетов', NULL, NULL)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (80, N'Кафедра культурологии', NULL, NULL)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (81, N'Курс "Безопасность жизнедеятельности"', NULL, NULL)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (82, N'Кафедра педагогики и психологии', NULL, NULL)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (83, N'Кафедра физического воспитания и спорта', NULL, NULL)
INSERT [dbo].[Departments] ([Id], [Name], [ShortName], [Faculty_Id]) VALUES (84, N'Кафедра философии', NULL, NULL)
SET IDENTITY_INSERT [dbo].[Departments] OFF