SET IDENTITY_INSERT [dbo].[Faculties] ON
INSERT [dbo].[Faculties] ([Id], [Name], [ShortName]) VALUES (1, N'Медицинский факультет', N'Медецинский')
INSERT [dbo].[Faculties] ([Id], [Name], [ShortName]) VALUES (2, N'Экономический факультет', N'Экономический')
INSERT [dbo].[Faculties] ([Id], [Name], [ShortName]) VALUES (3, N'Строительный факультет', N'Строительный')
INSERT [dbo].[Faculties] ([Id], [Name], [ShortName]) VALUES (4, N'Факультет политических и социальных наук', N'Политических и социальных наук')
INSERT [dbo].[Faculties] ([Id], [Name], [ShortName]) VALUES (5, N'Факультет прибалтийско-финской филологии и культуры', N'Прибалтийско-финской филологии и культуры')
INSERT [dbo].[Faculties] ([Id], [Name], [ShortName]) VALUES (6, N'Агротехнический факультет', N'Агротехнический')
INSERT [dbo].[Faculties] ([Id], [Name], [ShortName]) VALUES (7, N'Физико-технический факультет', N'Физико-технический')
INSERT [dbo].[Faculties] ([Id], [Name], [ShortName]) VALUES (8, N'Эколого-биологический факультет', N'Эколого-биологический')
INSERT [dbo].[Faculties] ([Id], [Name], [ShortName]) VALUES (9, N'Исторический факультет', N'Исторический')
INSERT [dbo].[Faculties] ([Id], [Name], [ShortName]) VALUES (10, N'Лесоинженерный факультет', N'Лесоинженерный')
INSERT [dbo].[Faculties] ([Id], [Name], [ShortName]) VALUES (11, N'Математический факультет', N'Математический')
INSERT [dbo].[Faculties] ([Id], [Name], [ShortName]) VALUES (12, N'Кафедра туризма', N'Туризма')
INSERT [dbo].[Faculties] ([Id], [Name], [ShortName]) VALUES (13, N'Юридический факультет', N'Юридический')
INSERT [dbo].[Faculties] ([Id], [Name], [ShortName]) VALUES (14, N'Горно-геологический факультет', N'Горно-геологический')
INSERT [dbo].[Faculties] ([Id], [Name], [ShortName]) VALUES (15, N'Филологический факультет', N'Филологический')
SET IDENTITY_INSERT [dbo].[Faculties] OFF