SET IDENTITY_INSERT [dbo].[Lecturers] ON
INSERT [dbo].[Lecturers] ([Id], [Lastname], [Firstname], [Middlename],  [Contacts], [Department_Id], [Rank_Id]) VALUES (1,	N'Воронин',		N'Анатолий',	N'Викторович',		N'voronin@psu.karelia.ru ', 71, 1)
INSERT [dbo].[Lecturers] ([Id], [Lastname], [Firstname], [Middlename],  [Contacts], [Department_Id], [Rank_Id]) VALUES (2,	N'Щеголева',	N'Людмила',		N'Владимировна',	N'schegoleva@psu.karelia.ru ', 71, 2)
INSERT [dbo].[Lecturers] ([Id], [Lastname], [Firstname], [Middlename],  [Contacts], [Department_Id], [Rank_Id]) VALUES (3,	N'Заика',		N'Юрий',		N'Васильевич',		N'zaika@krc.karelia.ru ', 71, 3)
INSERT [dbo].[Lecturers] ([Id], [Lastname], [Firstname], [Middlename],  [Contacts], [Department_Id], [Rank_Id]) VALUES (4,	N'Кузнецов',	N'Владимир',	N'Алексеевич',		N'kuznetcv@mail.ru ', 71, 3)
INSERT [dbo].[Lecturers] ([Id], [Lastname], [Firstname], [Middlename],  [Contacts], [Department_Id], [Rank_Id]) VALUES (5,	N'Морозов',		N'Евсей',		N'Викторович',		N'emorozov@karelia.ru ', 71, 3)
INSERT [dbo].[Lecturers] ([Id], [Lastname], [Firstname], [Middlename],  [Contacts], [Department_Id], [Rank_Id]) VALUES (6,	N'Воронов',		N'Роман',		N'Владимирович',	N'rvoronov@karelia.ru ', 71, 4)
INSERT [dbo].[Lecturers] ([Id], [Lastname], [Firstname], [Middlename],  [Contacts], [Department_Id], [Rank_Id]) VALUES (7,	N'Лазарев',		N'Алексей',		N'Викторович',		N'lazarev_av@sampo.ru ', 71, 4)
INSERT [dbo].[Lecturers] ([Id], [Lastname], [Firstname], [Middlename],  [Contacts], [Department_Id], [Rank_Id]) VALUES (8,	N'Насадкина',	N'Ольга',		N'Юрьевна',			N'onasad@psu.karelia.ru ', 71, 4)
INSERT [dbo].[Lecturers] ([Id], [Lastname], [Firstname], [Middlename],  [Contacts], [Department_Id], [Rank_Id]) VALUES (9,	N'Перепечко',	N'Сергей',		N'Николаевич',		N'persn@newmail.ru ', 71, 4)
INSERT [dbo].[Lecturers] ([Id], [Lastname], [Firstname], [Middlename],  [Contacts], [Department_Id], [Rank_Id]) VALUES (10,	N'Пешкова',		N'Ирина',		N'Валерьевна',		N'iaminova@karelia.ru ', 71, 4)
INSERT [dbo].[Lecturers] ([Id], [Lastname], [Firstname], [Middlename],  [Contacts], [Department_Id], [Rank_Id]) VALUES (11,	N'Шабаев',		N'Антон',		N'Игоревич',		N'ashabaev@karelia.ru ', 71, 4)
INSERT [dbo].[Lecturers] ([Id], [Lastname], [Firstname], [Middlename],  [Contacts], [Department_Id], [Rank_Id]) VALUES (12,	N'Жуков',		N'Артем',		N'Владимирович',	N'zhukov@karelia.ru ', 71, 5)
INSERT [dbo].[Lecturers] ([Id], [Lastname], [Firstname], [Middlename],  [Contacts], [Department_Id], [Rank_Id]) VALUES (13,	N'Кириленко',	N'Александр',	N'Николаевич',		N'kiritigr@rambler.ru ', 71, 5)
INSERT [dbo].[Lecturers] ([Id], [Lastname], [Firstname], [Middlename],  [Contacts], [Department_Id], [Rank_Id]) VALUES (14,	N'Косицын',		N'Дмитрий',		N'Петрович',		N'kositsyn@psu.karelia.ru ', 71, 5)
INSERT [dbo].[Lecturers] ([Id], [Lastname], [Firstname], [Middlename],  [Contacts], [Department_Id], [Rank_Id]) VALUES (15,	N'Сошкин',		N'Роман',		N'Владимирович',	N'soshkin@mail.ru ', 71, 5)
INSERT [dbo].[Lecturers] ([Id], [Lastname], [Firstname], [Middlename],  [Contacts], [Department_Id], [Rank_Id]) VALUES (16,	N'Суровцева',	N'Татьяна',		N'Генадьевна',		N'tsurovceva@psu.karelia.ru ', 71, 5)
INSERT [dbo].[Lecturers] ([Id], [Lastname], [Firstname], [Middlename],  [Contacts], [Department_Id], [Rank_Id]) VALUES (17,	N'Сысун',		N'Александр',	N'Валерьевич',		N'sysun@petrsu.ru ', 71, 5)
INSERT [dbo].[Lecturers] ([Id], [Lastname], [Firstname], [Middlename],  [Contacts], [Department_Id], [Rank_Id]) VALUES (18,	N'Попов',		N'Алексей',		N'Львович',			N'alex5431@mail.ru ', 71, 5)
INSERT [dbo].[Lecturers] ([Id], [Lastname], [Firstname], [Middlename],  [Contacts], [Department_Id], [Rank_Id]) VALUES (19,	N'Андреева',	N'Юлия',		N'Александровна',	N'julana2008@yandex.ru ', 71, 6)
INSERT [dbo].[Lecturers] ([Id], [Lastname], [Firstname], [Middlename],  [Contacts], [Department_Id], [Rank_Id]) VALUES (20,	N'Апанасик',	N'Анастасия',	N'Михайловна',		N'anastasiyamih@mail.ru ', 71, 6)
INSERT [dbo].[Lecturers] ([Id], [Lastname], [Firstname], [Middlename],  [Contacts], [Department_Id], [Rank_Id]) VALUES (21,	N'Богданов',	N'Андрей',		N'Викторович',		NULL, 71, 6)
INSERT [dbo].[Lecturers] ([Id], [Lastname], [Firstname], [Middlename],  [Contacts], [Department_Id], [Rank_Id]) VALUES (22,	N'Богданова',	N'Маргарита',	N'Владимировна',	N'bogdanov@karelia.ru ', 71, 6)
INSERT [dbo].[Lecturers] ([Id], [Lastname], [Firstname], [Middlename],  [Contacts], [Department_Id], [Rank_Id]) VALUES (23,	N'Власов',		N'Денис',		N'Петрович',		N'dpetrovich@onego.ru ', 71, 6)
INSERT [dbo].[Lecturers] ([Id], [Lastname], [Firstname], [Middlename],  [Contacts], [Department_Id], [Rank_Id]) VALUES (24,	N'Воронова',	N'Анна',		N'Михайловна',		N'voronova_am@petrsu.ru ', 71, 6)
INSERT [dbo].[Lecturers] ([Id], [Lastname], [Firstname], [Middlename],  [Contacts], [Department_Id], [Rank_Id]) VALUES (25,	N'Воропаев',	N'Антон',		N'Николаевич',		N'antonvoropaev@mail.ru ', 71, 6)
INSERT [dbo].[Lecturers] ([Id], [Lastname], [Firstname], [Middlename],  [Contacts], [Department_Id], [Rank_Id]) VALUES (26,	N'Гнеушева',	N'Наталья',		N'Владимировна',	N'natgn@goon.ru ', 71, 6)
INSERT [dbo].[Lecturers] ([Id], [Lastname], [Firstname], [Middlename],  [Contacts], [Department_Id], [Rank_Id]) VALUES (27,	N'Горинов',		N'Николай',		N'Александрович',	N'gorinov@karelia.ru ', 71, 6)
INSERT [dbo].[Lecturers] ([Id], [Lastname], [Firstname], [Middlename],  [Contacts], [Department_Id], [Rank_Id]) VALUES (28,	N'Горичева',	N'Руслана',		N'Сергеевна',		NULL, 71, 6)
INSERT [dbo].[Lecturers] ([Id], [Lastname], [Firstname], [Middlename],  [Contacts], [Department_Id], [Rank_Id]) VALUES (29,	N'Гусев',		N'Олег',		N'Валерьевич',		N'http://gusev.eleset.ru', 71, 6)
INSERT [dbo].[Lecturers] ([Id], [Lastname], [Firstname], [Middlename],  [Contacts], [Department_Id], [Rank_Id]) VALUES (30,	N'Ивашко',		N'Евгений',		N'Евгеньевич',		NULL, 71, 6)
INSERT [dbo].[Lecturers] ([Id], [Lastname], [Firstname], [Middlename],  [Contacts], [Department_Id], [Rank_Id]) VALUES (31,	N'Караваев',	N'Артем',		N'Михайлович',		N'http://karavaev.flowproblem.ru', 71, 6)
INSERT [dbo].[Lecturers] ([Id], [Lastname], [Firstname], [Middlename],  [Contacts], [Department_Id], [Rank_Id]) VALUES (32,	N'Лукашенко',	N'Олег',		N'Викторович',		NULL, 71, 6)
INSERT [dbo].[Lecturers] ([Id], [Lastname], [Firstname], [Middlename],  [Contacts], [Department_Id], [Rank_Id]) VALUES (33,	N'Могилев',		N'Максим',		N'Викторович',		N'mcsymco@gmail.com ', 71, 6)
INSERT [dbo].[Lecturers] ([Id], [Lastname], [Firstname], [Middlename],  [Contacts], [Department_Id], [Rank_Id]) VALUES (34,	N'Пустовит',	N'Татьяна',		N'Михайловна',		N'nola@psu.karelia.ru ', 71, 6)
INSERT [dbo].[Lecturers] ([Id], [Lastname], [Firstname], [Middlename],  [Contacts], [Department_Id], [Rank_Id]) VALUES (35,	N'Савинов',		N'Григорий',	N'Александрович',	N'mail@gyrr.ru ', 71, 6)
INSERT [dbo].[Lecturers] ([Id], [Lastname], [Firstname], [Middlename],  [Contacts], [Department_Id], [Rank_Id]) VALUES (36,	N'Смолий',		N'Юлия',		N'Андреевна',		N'Julia.Sidorova@metsopartners.com ', 71, 6)
INSERT [dbo].[Lecturers] ([Id], [Lastname], [Firstname], [Middlename],  [Contacts], [Department_Id], [Rank_Id]) VALUES (37,	N'Соколов',		N'Владислав',	N'Евгеньевич',		N'svl@karelia.ru ', 71, 6)
INSERT [dbo].[Lecturers] ([Id], [Lastname], [Firstname], [Middlename],  [Contacts], [Department_Id], [Rank_Id]) VALUES (38,	N'Фомина',		N'Елена',		N'Анатольевна',		N'foelan@petrsu.ru ', 71, 6)
INSERT [dbo].[Lecturers] ([Id], [Lastname], [Firstname], [Middlename],  [Contacts], [Department_Id], [Rank_Id]) VALUES (39,	N'Хентов',		N'Сергей',		N'Владимирович',	N'sergey.khentov@gmail.com ', 71, 6)
INSERT [dbo].[Lecturers] ([Id], [Lastname], [Firstname], [Middlename],  [Contacts], [Department_Id], [Rank_Id]) VALUES (40,	N'Шлей',		N'Михаил',		N'Дмитриевич',		NULL, 71, 6)
INSERT [dbo].[Lecturers] ([Id], [Lastname], [Firstname], [Middlename],  [Contacts], [Department_Id], [Rank_Id]) VALUES (41,	N'Панченко',	N'Татьяна',		N'Борисовна',		N'pmik@petrsu.ru ', 71, 7)
INSERT [dbo].[Lecturers] ([Id], [Lastname], [Firstname], [Middlename],  [Contacts], [Department_Id], [Rank_Id]) VALUES (42,	N'Прохоров',	N'Максим',		N'Андреевич',		NULL, 71, 8)
SET IDENTITY_INSERT [dbo].[Lecturers] OFF