SET IDENTITY_INSERT [dbo].[Tutorials] ON
INSERT [dbo].[Tutorials] ([Id], [Name], [ShortName]) VALUES (1, N'Дискретная математика', NULL)
INSERT [dbo].[Tutorials] ([Id], [Name], [ShortName]) VALUES (2, N'Доп. разделы инф. и прогр.', NULL)
INSERT [dbo].[Tutorials] ([Id], [Name], [ShortName]) VALUES (3, N'Комп. Практикум', NULL)
INSERT [dbo].[Tutorials] ([Id], [Name], [ShortName]) VALUES (4, N'Практикум по программированию', NULL)
INSERT [dbo].[Tutorials] ([Id], [Name], [ShortName]) VALUES (5, N'Программирование', NULL)
INSERT [dbo].[Tutorials] ([Id], [Name], [ShortName]) VALUES (6, N'Теор. основы информатики', NULL)
INSERT [dbo].[Tutorials] ([Id], [Name], [ShortName]) VALUES (7, N'Дифф. уравнения', NULL)
INSERT [dbo].[Tutorials] ([Id], [Name], [ShortName]) VALUES (8, N'Комбинаторные алгоритмы', NULL)
INSERT [dbo].[Tutorials] ([Id], [Name], [ShortName]) VALUES (9, N'ОО анализ и программирование', NULL)
INSERT [dbo].[Tutorials] ([Id], [Name], [ShortName]) VALUES (10, N'Теория алгоритмов', NULL)
INSERT [dbo].[Tutorials] ([Id], [Name], [ShortName]) VALUES (11, N'Методы оптимизации', NULL)
INSERT [dbo].[Tutorials] ([Id], [Name], [ShortName]) VALUES (12, N'Оптимизация и мат. методы принятия решений', NULL)
INSERT [dbo].[Tutorials] ([Id], [Name], [ShortName]) VALUES (13, N'Прикладные методы оптимизации', NULL)
INSERT [dbo].[Tutorials] ([Id], [Name], [ShortName]) VALUES (14, N'С/к Проекты', NULL)
INSERT [dbo].[Tutorials] ([Id], [Name], [ShortName]) VALUES (15, N'С/к Аудит управления ИКТ компании', NULL)
INSERT [dbo].[Tutorials] ([Id], [Name], [ShortName]) VALUES (16, N'С/к Технологии построения Интернета', NULL)
INSERT [dbo].[Tutorials] ([Id], [Name], [ShortName]) VALUES (17, N'Теория вероятностей и МС', NULL)
INSERT [dbo].[Tutorials] ([Id], [Name], [ShortName]) VALUES (18, N'Проектирование ИС', NULL)
INSERT [dbo].[Tutorials] ([Id], [Name], [ShortName]) VALUES (19, N'Эконометрика', NULL)
INSERT [dbo].[Tutorials] ([Id], [Name], [ShortName]) VALUES (20, N'Эффект. прогр. в Oracle', NULL)
INSERT [dbo].[Tutorials] ([Id], [Name], [ShortName]) VALUES (21, N'Корпоративные ИС', NULL)
INSERT [dbo].[Tutorials] ([Id], [Name], [ShortName]) VALUES (22, N'Исследование операций', NULL)
INSERT [dbo].[Tutorials] ([Id], [Name], [ShortName]) VALUES (23, N'Компьютерный практикум', NULL)
INSERT [dbo].[Tutorials] ([Id], [Name], [ShortName]) VALUES (24, N'Логистика', NULL)
INSERT [dbo].[Tutorials] ([Id], [Name], [ShortName]) VALUES (25, N'Орг. обеспечение. инф. безопасности', NULL)
INSERT [dbo].[Tutorials] ([Id], [Name], [ShortName]) VALUES (26, N'С/к Совр. технологии высокопроизв. вычислений', NULL)
INSERT [dbo].[Tutorials] ([Id], [Name], [ShortName]) VALUES (27, N'С/к Комб. алгоритмы. эксп. сложности', NULL)
INSERT [dbo].[Tutorials] ([Id], [Name], [ShortName]) VALUES (28, N'С/к Основы потоков в сетях', NULL)
INSERT [dbo].[Tutorials] ([Id], [Name], [ShortName]) VALUES (29, N'Теория управления', NULL)
INSERT [dbo].[Tutorials] ([Id], [Name], [ShortName]) VALUES (30, N'Управление производством', NULL)
INSERT [dbo].[Tutorials] ([Id], [Name], [ShortName]) VALUES (31, N'С/к основы финансовой математики', NULL)
INSERT [dbo].[Tutorials] ([Id], [Name], [ShortName]) VALUES (32, N'С/к структуры данных комб. алг.', NULL)
INSERT [dbo].[Tutorials] ([Id], [Name], [ShortName]) VALUES (33, N'Случайные процессы', NULL)
INSERT [dbo].[Tutorials] ([Id], [Name], [ShortName]) VALUES (34, N'Спецсеминар', NULL)
INSERT [dbo].[Tutorials] ([Id], [Name], [ShortName]) VALUES (35, N'Теория принятия решений', NULL)
INSERT [dbo].[Tutorials] ([Id], [Name], [ShortName]) VALUES (36, N'Управление ЖЦ ИС', NULL)
INSERT [dbo].[Tutorials] ([Id], [Name], [ShortName]) VALUES (37, N'Управление инф. рисками', NULL)
INSERT [dbo].[Tutorials] ([Id], [Name], [ShortName]) VALUES (38, N'С/к Дополнительные главы комбинаторики', NULL)
INSERT [dbo].[Tutorials] ([Id], [Name], [ShortName]) VALUES (39, N'С/к Современные системы управления', NULL)
INSERT [dbo].[Tutorials] ([Id], [Name], [ShortName]) VALUES (40, N'Управление производством', NULL)
SET IDENTITY_INSERT [dbo].[Tutorials] OFF
