// <auto-generated />

using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Timetable.Data.Migrations.Auth
{
    public sealed partial class Add_users_and_roles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_users_and_roles));
        
        string IMigrationMetadata.Id
        {
            get { return "201304201431152_Add_users_and_roles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
