// <auto-generated />
namespace Timetable.Data.Migrations.Schedule
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Add_Position_column_to_the_Times_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_Position_column_to_the_Times_table));
        
        string IMigrationMetadata.Id
        {
            get { return "201305191752266_Add_Position_column_to_the_Times_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
