// <auto-generated />

using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Timetable.Data.Migrations.Schedule
{
    public sealed partial class Add_StudyYears_and_AuditoriumTypes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_StudyYears_and_AuditoriumTypes));
        
        string IMigrationMetadata.Id
        {
            get { return "201304061253125_Add_StudyYears_and_AuditoriumTypes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
