// <auto-generated />
namespace Timetable.Data.Migrations.Schedule
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Remove_StudyYear_entity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Remove_StudyYear_entity));
        
        string IMigrationMetadata.Id
        {
            get { return "201305122003080_Remove_StudyYear_entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
