// <auto-generated />

using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Timetable.Data.Migrations.Schedule
{
    public sealed partial class Add_branches : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_branches));
        
        string IMigrationMetadata.Id
        {
            get { return "201303040739543_Add_branches"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
