// <auto-generated />

using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Timetable.Data.Migrations.Schedule
{
    public sealed partial class Initial_create : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initial_create));
        
        string IMigrationMetadata.Id
        {
            get { return "201303031905385_initial_create"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
