// <auto-generated />
namespace Timetable.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddFacultyAndRemoveDepartmentRefFromSpeciality : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddFacultyAndRemoveDepartmentRefFromSpeciality));
        
        string IMigrationMetadata.Id
        {
            get { return "201210262202509_AddFacultyAndRemoveDepartmentRefFromSpeciality"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
