// <auto-generated />
namespace Timetable.Data.Migrations.Schedule
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Add_AutoDeleteField_In_Schedules : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_AutoDeleteField_In_Schedules));
        
        string IMigrationMetadata.Id
        {
            get { return "201307120626393_Add_AutoDeleteField_In_Schedules"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
