// <auto-generated />
namespace Timetable.Data.Migrations.Schedule
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Foreign_keys_updated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Foreign_keys_updated));
        
        string IMigrationMetadata.Id
        {
            get { return "201306070734041_Foreign_keys_updated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
