// <auto-generated />
namespace Timetable.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Add_positions_for_a_lecturers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_positions_for_a_lecturers));
        
        string IMigrationMetadata.Id
        {
            get { return "201302241354432_Add_positions_for_a_lecturers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
